openapi: "3.0.0"

info:
  $ref: ./info/index.yaml

servers:
  - url: https://creamy-app.com/api/v1
    description: Staging Server
  - url: http://localhost:8080
    description: Development Server

paths:
  $ref: ./paths/index.yaml

components:
  securitySchemes:
    $ref: './security/index.yaml'

  schemas:
    AppUser:
      $ref: './schemas/user.yaml'
