openapi: "3.0.0"

info:
  description: "マッチングアプリ「creamy」 バックエンドAPI仕様書"
  version: "1.0.0"
  title: "creamy API"

servers:
  - url: https://creamy-app.com/api/v1
    description: "Staging Server"
  - url: http://localhost:8080
    description: "Development Server"

tags:
  - name: "user"
    description: "Operations about user"

paths:
  $ref: "./paths/_index.yaml"

components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: Credentials or access token for API

  schemas:
    $ref: "./schemas/_index.yaml"

  responses:
    $ref: "./responses/_index.yaml"
