openapi: "3.0.0"

info:
  $ref: "./info/index.yaml"

servers:
  - url: https://creamy-app.com/api/v1
    description: "Staging Server"
  - url: http://localhost:8080
    description: "Development Server"

tags:
  - name: "user"
    description: "Operations about user"

paths:
  $ref: "./paths/_index.yaml"

components:
  securitySchemes:
    $ref: "./security/_index.yaml"

  schemas:
    $ref: "./schemas/_index.yaml"

  responses:
    $ref: "./responses/_index.yaml"
