openapi: 3.0.0
info:
  description: マッチングアプリ「creamy」 バックエンドAPI仕様書
  version: 1.0.0
  title: creamy API
paths:
  "/pet/{petId}":
    get:
      summary: ペット情報API
      description: 指定されたpetIdの情報を返します
      parameters:
        - name: petId
          in: path
          description: 取得したいペットのID
          required: true
          type: integer
          format: int64
      responses:
        "200":
          description: 成功時のレスポンス
          schema:
            type: object
            properties:
              id:
                type: integer
                format: int64
              name:
                type: string
                example: doggie
